### ISSUE TITLE
practica 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-yaritzaov123#1]
[Uploading práctica Yaritza Osorio Villegas.docx…]()

**Comment by yanet02** [comment]
18% Está bien hecha tu trabajo, solo le faltó poner los resultados que obtuviste en base a la realización de tu trabajo y estructurarlo mejor!

**Comment by yaritzaov123** [comment]
[Uploading ejercicios.docx…]()
